name: Test zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
      - develop
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: パッケージをインストール
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run tests for zenn-markdown-html
        run: pnpm test
        working-directory: packages/zenn-markdown-html

      - name: Run tests for zenn-cli-wysiwyg
        run: pnpm test
        working-directory: packages/zenn-cli-wysiwyg

      - name: Run tests for zenn-wysiwyg-editor
        run: pnpm test:node
        working-directory: packages/zenn-wysiwyg-editor

  test-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Setup Playwright Browsers
        run: pnpm -F zenn-wysiwyg-editor exec playwright install --with-deps ${{ matrix.browser }}

      - name: Run vitest browser mode tests
        run: pnpm -F zenn-wysiwyg-editor test:browser --project=${{ matrix.browser }}
